# Generated by Django 5.2.1 on 2025-06-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_google_credentials_googlecredentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleCredentials',
        ),
    ]
