# Generated by Django 5.2.1 on 2025-06-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
