# Generated by Django 5.2.1 on 2025-06-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_googlecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_credentials',
            field=models.JSONField(blank=True, help_text='Credenciais de acesso ao Google Calendar', null=True),
        ),
    ]
