# Generated by Django 5.2.1 on 2025-06-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_google_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
