# Generated by Django 5.2.1 on 2025-09-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_google_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_credentials',
        ),
        migrations.AddField(
            model_name='projectphase',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
