# Generated by Django 5.2.1 on 2025-09-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_google_credentials_projectphase_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphase',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='start_date',
        ),
    ]
